[D020105][FTR] add min coverage

diff --git a/.github/workflows/unit.yml b/.github/workflows/unit.yml
--- a/.github/workflows/unit.yml
+++ b/.github/workflows/unit.yml
@@ -50,5 +50,12 @@ jobs:
       uses: codecov/codecov-action@v2.1.0
       with:
         files: clover.xml
-        fail_ci_if_error: true # optional (default = false)
-        verbose: true # optional (default = false)
+#        fail_ci_if_error: true # optional (default = false)
+#        verbose: true # optional (default = false)
+    - name: Check minimum required test coverage
+      run: |
+        CODE_COVERAGE=$(vendor/bin/coverage-checker clover.xml 90 --processor=clover-coverage)
+        echo ${CODE_COVERAGE}
+        if [[ ${CODE_COVERAGE} == *"test coverage, got"* ]] ; then
+          exit 1;
+        fi
